language: python
python:
  - "2.7"

env:
  global:
    - GH_REF: github.com/aneasystone/ci-doc-chinese.git
    - secure: ""

cache:
  directories:
  - $HOME/.cache/pip

sudo: false

install:
  - pip install --upgrade pip
  - pip install "Sphinx==1.2.3"
  - pip install "sphinxcontrib-phpdomain"
  - cd cilexer && python setup.py install && cd ..

script:
  - make html

# Flags used here, not in `make html`:
#  -n   Run in nit-picky mode. Currently, this generates warnings for all missing references.
#  -W   Turn warnings into errors. This means that the build stops at the first warning and sphinx-build exits with exit status 1.
